
import React, { useState } from 'react';
import { motion } from 'framer-motion';
import { FaIndustry, FaBolt, FaTrash, FaWater, FaCog, FaTools, FaTint } from 'react-icons/fa';
import '../styles/Services.css';

const Services = () => {
  const [selectedService, setSelectedService] = useState(null);

  const services = [
    {
      category: "Consulting & Project Services",
      items: [
        {
          icon: <FaIndustry />,
          title: "Common Effluent Treatment Plants",
          description: "Custom CETP solutions for industrial waste management",
          details: "A Common Effluent Treatment Plant (CETP) is a centralized facility designed to treat industrial effluents from multiple industries, ensuring that wastewater meets environmental standards before being discharged into water bodies or reused. CETPs are crucial for managing pollution, especially in areas with dense industrial activity, as they help reduce the burden on individual companies to build their own treatment plants. These plants typically use a combination of physical, chemical, and biological processes to treat the effluent, thereby preventing the contamination of water resources and promoting sustainable industrial practices."
        },
        {
          icon: <FaIndustry />,
          title: "Effluent Treatment Plants",
          description: "Custom ETP solutions for industrial waste management",
          details: "An Effluent Treatment Plant (ETP) is an industrial facility designed to treat wastewater (or effluent) before it is discharged into the environment or reused. ETPs are used by industries to ensure that the water released does not pollute the surrounding environment or violate regulatory standards. "
        },
        {
          icon: <FaTrash />,
          title: "Municipal Solid Waste Management",
          description: "Urban waste management solutions",
          details: "Municipal Solid Waste Management (MSWM) refers to the process of collecting, transporting, treating, and disposing of waste generated by households, commercial establishments, and institutions within a municipality."
        },
        {
          icon: <FaBolt />,
          title: "Waste to Energy Plants",
          description: "Converting waste into sustainable energy",
          details: "Waste-to-Energy (WTE) plants are facilities that convert non-recyclable municipal solid waste into usable energy, typically in the form of electricity or heat. These plants use various technologies to burn or process waste, generating energy as a byproduct.Waste-to-Energy (WTE) plants are facilities that convert non-recyclable municipal solid waste into usable energy, typically in the form of electricity or heat. These plants use various technologies to burn or process waste, generating energy as a byproduct."
        },
        {
          icon: <FaWater />,
          title: "Sewage Treatment Plants",
          description: "Design and implementation of modern STP solutions",
          details: "A Sewage Treatment Plant (STP) is a facility designed to treat domestic wastewater or sewage, ensuring that harmful pollutants are removed before the water is released into the environment or reused. STPs typically use physical, chemical, and biological processes to treat the wastewater, reducing its pollution load. These plants are essential for maintaining public health and protecting water bodies from contamination, especially in urban and densely populated areas. By treating sewage, STPs help improve sanitation, prevent the spread of waterborne diseases, and promote sustainable water management."
        },
        {
          icon: <FaWater/>,
          title: "Detailed Project Reports",
          description: "Comprehensive analysis and feasibility studies for environmental projects",
          details: "Details about Detailed Project Reports go here."
        },
      ],
    },{
      category: "Engineering & Technical Services",
      items: [
        {
          icon: <FaCog />,
          title: "Engineering Services",
          description: "Expert technical consulting and implementation",
          details: "Details about Engineering Services go here."
        },
        {
          icon: <FaTools />,
          title: "CETP Installation & Operation",
          description: "End-to-end sewage treatment solutions",
          details: "Details about CETP Installation & Operation go here."
        },
        {
          icon: <FaTools />,
          title: "STP Installation & Operation",
          description: "End-to-end sewage treatment solutions",
          details: "Details about STP Installation & Operation go here."
        },
        {
          icon: <FaCog />,
          title: "ETP Installation & Operation",
          description: "Industrial effluent treatment systems",
          details: "Details about ETP Installation & Operation go here."
        },
        {
          icon: <FaTint />,
          title: "Rain Water Harvesting",
          description: "Sustainable water conservation systems",
          details: "Details about Rain Water Harvesting go here."
        }
      ]
    }
  ];

  return (
    <div className="services">
      <div className="services-hero">
        <h1>Our Services</h1>
        <div className="hero-line"></div>
        <p>Comprehensive Environmental Solutions for a Sustainable Future</p>
      </div>

      {selectedService ? (
        <motion.div
          className="modal-view"
          initial={{ opacity: 0, scale: 0.9 }}
          animate={{ opacity: 1, scale: 1 }}
          transition={{ duration: 0.3 }}
        >
          <div className="modal-content">
            <h2>{selectedService.title}</h2>
            <p>{selectedService.details}</p>
            <motion.button
              className="back-btn"
              whileHover={{ scale: 1.05 }}
              whileTap={{ scale: 0.95 }}
              onClick={() => setSelectedService(null)}
            >
              Back
            </motion.button>
          </div>
        </motion.div>
      ) : (
        services.map((serviceCategory, idx) => (
          <div key={idx} className="services-section">
            <h2 className="category-title">{serviceCategory.category}</h2>
            <div className="services-grid">
              {serviceCategory.items.map((service, index) => (
                <motion.div
                  key={index}
                  className="service-card"
                  whileHover={{ scale: 1.03 }}
                  onClick={() => setSelectedService(service)}
                >
                  <div className="service-icon">{service.icon}</div>
                  <h3>{service.title}</h3>
                  <p>{service.description}</p>
                  <motion.button
                    className="learn-more"
                    whileHover={{ scale: 1.05 }}
                    whileTap={{ scale: 0.95 }}
                  >
                    Learn More
                  </motion.button>
                </motion.div>
              ))}
            </div>
          </div>
        ))
      )}
    </div>
  );
};

export default Services;
